# Generated by Django 6.0.2 on 2026-03-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
