# Generated by Django 6.0.2 on 2026-03-09 13:37

import djangoyearlessdate.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=djangoyearlessdate.models.YearlessDateField(blank=True, max_length=4, null=True),
        ),
    ]
