# Generated by Django 6.0.2 on 2026-03-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_birthday'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='members_mem_phone_94f004_idx',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_number'], name='members_mem_phone_n_28ee55_idx'),
        ),
        migrations.AddField(
            model_name='firsttimers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='firsttimers',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
    ]
