# Generated by Django 6.0.2 on 2026-06-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_firsttimers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
