# Generated by Django 6.0.2 on 2026-06-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
    ]
