# Generated by Django 6.0.2 on 2026-06-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE members 
                ADD COLUMN IF NOT EXISTS birthday varchar(4);
            """,
            reverse_sql="""
                ALTER TABLE members 
                DROP COLUMN IF EXISTS birthday;
            """
        ),
    ]
