# Generated by Django 6.0.2 on 2026-03-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connect_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('theme', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('connect_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect_groups.connectgroup')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype')),
            ],
            options={
                'indexes': [models.Index(fields=['service_date'], name='services_se_service_674f67_idx'), models.Index(fields=['service_type'], name='services_se_service_57f6a4_idx')],
            },
        ),
    ]
