# Generated by Django 6.0.2 on 2026-08-11 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0009_auto_20260625_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorates_led', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_assisted', to='members.member')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to='members.member')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='departments.directorate')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='departments.department')),
                ('unit_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_led', to='members.member', verbose_name='Unit Head / Assistant HOD')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, help_text='e.g. Camera Operator, Graphics Designer, Stream Technician...', max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='members.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='departments.unit')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'indexes': [models.Index(fields=['member'], name='departments_member__a8de9a_idx'), models.Index(fields=['department'], name='departments_departm_37c5b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'department'), name='unique_member_department')],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['department'], name='departments_departm_908062_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_head'], name='departments_unit_he_87a7e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('name', 'department')},
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['member'], name='departments_member__66680a_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['unit'], name='departments_unit_id_e9fccf_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitmembership',
            constraint=models.UniqueConstraint(fields=('member', 'unit'), name='unique_member_unit'),
        ),
    ]
