# Generated by Django 6.0.2 on 2026-03-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('pastors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('meeting_day', models.CharField(max_length=20)),
                ('meeting_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('connect_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_groups.connectgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectGroupPastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('connect_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect_groups.connectgroup')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastors.pastor')),
            ],
        ),
    ]
