# Generated by Django 6.0.2 on 2026-03-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('first_timer', 'First Timer'), ('member', 'Member'), ('worker', 'Worker'), ('visitor', 'Visitor')], max_length=20)),
                ('check_in_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'indexes': [models.Index(fields=['service'], name='attendance__service_a282dc_idx'), models.Index(fields=['member'], name='attendance__member__481773_idx'), models.Index(fields=['created_at'], name='attendance__created_a6132d_idx'), models.Index(fields=['service', 'member'], name='attendance__service_bb20a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'service'), name='unique_attendance_per_service')],
            },
        ),
    ]
