# Generated by Django 6.0.2 on 2026-03-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_method',
        ),
    ]
